# [Note] We have a separate pipeline for publishing the package to an ADO feed
# to be able to consume it from microsoft internal libraries with already
# established service connection. ADO currently only supports one nuget feed connection.
# If ADO allows adding the Github Nuget connection endpoint, 
# this pipeline may be disabled and start consuming Shift Core from Github Nuget endpoint.

variables:
  major: 1
  minor: 1
  patch: $[counter(variables['minor'], 0)]
  shiftVersion: $(major).$(minor).$(patch) # for versioning shift builds

resources:
  repositories:
    - repository: shift
      type: github
      name: microsoft/shift
      endpoint: github.com_chaehonglee
      ref: refs/heads/main

pool:
  name: Analog-1ES-Server2022

jobs:
- job:
  timeoutInMinutes: 360
  steps:
  - checkout: self
  - checkout: shift
  
  # get latest nuget tool installer
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec:
      checkLatest: true

  # restore nuget
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**\Shift.sln'
      feedsToUse: 'select'

  # build shift 
  - task: VSBuild@1
    inputs:
      solution: '**\Shift.sln'
      vsVersion: '17.0'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      maximumCpuCount: true
      restoreNugetPackages: true
      msbuildArgs: '-property:Version=$(shiftVersion)'
  
  # publish nuget
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '8115054f-1c74-4928-a9ab-de4769e7d6ae/2c4a69a6-14e2-4ffb-814a-95334a7e9366'