name: Prerelease

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checking out Code
      uses: actions/checkout@v2
    
    - name: Get version
      id: version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        format: "${major}.${minor}.${patch}-prerelease"

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: true

    - name: Restoring Packages
      run: dotnet restore

    - name: Building Project(s)
      run: >-
        dotnet build 
        -p:Version=${{ steps.version.outputs.version }} 
        --no-restore

    - name: Pack Shift.Core NuGet
      run: >-
        dotnet pack Shift.Core
        --configuration Release
        -p:PackageVersion=${{ steps.version.outputs.version }}
        -p:PackageId=Microsoft.Shift.Core

    - name: Publish Nuget
      run: >-
        dotnet nuget push 
        --api-key ${{ secrets.NUGET_PACKAGES_PAT }}
        --source https://api.nuget.org/v3/index.json
        "**/*Shift.Core*.nupkg"
    
    - name: Azure pipeline trigger
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/microsoft/Analog
        azure-pipeline-name: 'mixedreality.devtools-Official'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

