name: Prerelease

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    env:
      BUILD_VERSION: '0.0.0-alpha'

    runs-on: windows-2022

    steps:
    - name: Checking out Code
      uses: actions/checkout@v2

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: true

    - name: Restoring Packages
      run: dotnet restore

    - name: Building Project(s)
      run: dotnet build -p:Version=$BUILD_VERSION --no-restore

    - name: Pack Shift.Core NuGet
      run: >-
        dotnet pack Shift.Core
        --configuration Release
        -p:PackageVersion=$BUILD_VERSION

    - name: Publish Nuget
      run: >-
        dotnet nuget push 
        --api-key ${{ secrets.NUGET_PACKAGES_PAT }}
        --source https://api.nuget.org/v3/index.json
        "**/*.nupkg"
    
    - name: Azure pipeline trigger
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/microsoft/Analog
        azure-pipeline-name: 'mixedreality.devtools-Official'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

