name: Official - Publish NuGet

on:
  push:
    branches: [ "main" ]

variables:
  major: 0
  minor: 0
  patch: $[counter(variables['minor'], 0)]
  shiftVersion: $(major).$(minor).$(patch)

jobs:
  build:

    runs-on: windows-2022

    steps:

    - name: Checking out Code
      uses: actions/checkout@v2

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: false

    - name: Restoring Packages
      run: dotnet restore

    - name: Building Project(s)
      run: dotnet build --no-restore

    - name: Pack Shift.Core NuGet
      run: dotnet pack Shift.Core --configuration Release -p:PackageVersion=$(shiftVersion)

    - name: Publish Nuget
      run: >-
        dotnet nuget push 
        --api-key ${{ secrets.NUGET_PACKAGES_PAT }}
        --source https://nuget.pkg.github.com/microsoft/index.json
        "**/*.nupkg"
    
    - name: Azure pipeline trigger
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/microsoft/Analog
        azure-pipeline-name: 'mixedreality.devtools-Official'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

