name: Prerelease

on:
  push:
    branches: [ "main" ]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checking out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Get version
      id: version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        bump_each_commit: false
        format: "${major}.${minor}.${patch}"
        tag_prefix:
        
    - name: Generate Git Tag
      uses: EndBug/latest-tag@latest
      with:
        ref: ${{ steps.version.outputs.version }}

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: true

    - name: Restoring Packages
      run: dotnet restore

    - name: Building Project(s)
      run: >-
        dotnet build 
        -p:Version=${{ steps.version.outputs.version }}
        --no-restore

    - name: Publish Nuget for public comsumption
      run: >-
        dotnet nuget push 
        --api-key ${{ secrets.NUGET_PACKAGES_PAT }}
        --source https://api.nuget.org/v3/index.json
        "**/*.nupkg"

    - name: Publish Nuget for internal consumption
      run: >-
        dotnet nuget push
        --api-key ${{ secrets.AZURE_DEVOPS_TOKEN }}
        --source "analog.aie.engineeringefficiency-upstream"
        "**/*.nupkg"