name: Prerelease

on:
  push:
    branches: [ "main" ]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checking out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: true

    - name: Restoring Packages
      run: dotnet restore

    - name: Building Project(s)
      run: >-
        dotnet build 
        -p:Version=${{ steps.version.outputs.version }}
        --no-restore